sudo: required
services:
  - docker

script:
  - docker build -t lewisli1020/node .
  - docker images lewisli1020/node

before_deploy:
  - docker login -u lewisli1020 -p Kaho5016223986

deploy:
  provider: script
  script: docker push lewisli1020/node
  on:
    branch: master